version: "3"
services:
  mysql8:
    image: mysql:8.0
    #重启策略
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    #挂载文件
    volumes:
      #初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/

    #端口映射
    ports:
      - "13316:3306"
